#!/usr/bin/env node
/**
 * scripts/agent-doc.js
 * Extracts semantic tags (@ai-invariant, @ai-context, @ai-connection) from code
 * and generates docs/architecture/SYSTEM_MAP.md.
 */
const fs = require('fs');
const path = require('path');

const CONFIG = {
    include: ['.js', '.ts', '.jsx', '.tsx', '.py', '.rb', '.go', '.rs'],
    exclude: ['node_modules', 'dist', 'build', 'coverage', '.git'],
    outputFile: 'docs/architecture/SYSTEM_MAP.md'
};

async function scanDir(dir, fileList = []) {
    const files = await fs.promises.readdir(dir);
    await Promise.all(files.map(async (file) => {
        const filePath = path.join(dir, file);
        if (CONFIG.exclude.some(ex => filePath.includes(ex))) return;

        const stat = await fs.promises.stat(filePath);
        if (stat.isDirectory()) {
            await scanDir(filePath, fileList);
        } else {
            if (CONFIG.include.includes(path.extname(file))) {
                fileList.push(filePath);
            }
        }
    }));
    return fileList;
}

function extractTags(content) {
    const tags = [];
    // Regex to match block comments /** ... */
    const commentRegex = /\/\*\*([\s\S]*?)\*\//g;
    let match;

    while ((match = commentRegex.exec(content)) !== null) {
        const commentBlock = match[1];

        // Extract specific tags
        const tagTypes = ['ai-invariant', 'ai-context', 'ai-connection'];
        tagTypes.forEach(type => {
            const tagRegex = new RegExp(`@${type}\\s+(.*)`, 'g');
            let tagMatch;
            while ((tagMatch = tagRegex.exec(commentBlock)) !== null) {
                tags.push({
                    type: type,
                    content: tagMatch[1].trim()
                });
            }
        });
    }
    return tags;
}

function generateMarkdown(mapData) {
    let md = `# SYSTEM MAP (AgentDoc)\n\n`;
    md += `> Auto-generated by \`npm run bmad:doc\`. DO NOT EDIT MANUALLY.\n\n`;
    md += `This document maps the semantic context, invariants, and connections of the codebase.\n\n`;

    if (Object.keys(mapData).length === 0) {
        md += `*No AgentDoc tags found yet. Start adding \`@ai-context\` to your code!*`;
        return md;
    }

    for (const [file, tags] of Object.entries(mapData)) {
        if (tags.length === 0) continue;

        md += `## 📄 \`${file}\`\n`;

        const context = tags.filter(t => t.type === 'ai-context');
        const invariants = tags.filter(t => t.type === 'ai-invariant');
        const connections = tags.filter(t => t.type === 'ai-connection');

        if (context.length > 0) {
            md += `### 🧠 Context\n`;
            context.forEach(t => md += `- ${t.content}\n`);
        }

        if (invariants.length > 0) {
            md += `### 🛡️ Invariants (DO NOT BREAK)\n`;
            invariants.forEach(t => md += `- 🔴 **${t.content}**\n`);
        }

        if (connections.length > 0) {
            md += `### 🔗 Connections\n`;
            connections.forEach(t => md += `- ➡️ ${t.content}\n`);
        }
        md += `\n---\n\n`;
    }
    return md;
}

// Qdrant Configuration
const QDRANT_URL = 'http://localhost:6333';
const COLLECTION_NAME = 'bmad_agent_memory';

async function qdrantRequest(endpoint, method = 'GET', body = null) {
    try {
        const options = {
            method,
            headers: { 'Content-Type': 'application/json' }
        };
        if (body) options.body = JSON.stringify(body);

        const response = await fetch(`${QDRANT_URL}${endpoint}`, options);
        return await response.json();
    } catch (e) {
        console.error(`❌ Qdrant Error (${endpoint}):`, e.message);
        return null;
    }
}

async function ensureCollection() {
    const collections = await qdrantRequest('/collections');
    const exists = collections?.result?.collections?.some(c => c.name === COLLECTION_NAME);

    if (!exists) {
        console.log(`⚙️ Creating Qdrant collection: ${COLLECTION_NAME}`);
        await qdrantRequest(`/collections/${COLLECTION_NAME}`, 'PUT', {
            vectors: { size: 384, distance: 'Cosine' } // Using 384 for standard small models (all-MiniLM-L6-v2)
        });
    }
}

// Simple mock embedding for demonstration (In production, use a local model or API)
// This creates a deterministic "fake" vector based on string content to allow storage testing
function mockEmbedding(text) {
    const vector = new Array(384).fill(0);
    for (let i = 0; i < text.length; i++) {
        vector[i % 384] = (vector[i % 384] + text.charCodeAt(i)) / 255; // Normalize roughly
    }
    return vector;
}

async function syncToQdrant(mapData) {
    await ensureCollection();

    let idCounter = Date.now();
    const project = path.basename(process.cwd());
    const entries = Object.entries(mapData);

    const pointPromises = [];
    for (let i = 0; i < entries.length; i++) {
        const [file, tags] = entries[i];
        for (let j = 0; j < tags.length; j++) {
            const tag = tags[j];
            const id = idCounter++;
            pointPromises.push(
                (async () => ({
                    id,
                    vector: await mockEmbedding(tag.content),
                    payload: {
                        file: file,
                        type: tag.type,
                        content: tag.content,
                        project: project
                    }
                }))()
            );
        }
    }

    const points = await Promise.all(pointPromises);

    if (points.length > 0) {
        console.log(`🚀 Sending ${points.length} points to Qdrant...`);
        const result = await qdrantRequest(`/collections/${COLLECTION_NAME}/points?wait=true`, 'PUT', {
            points: points
        });
        if (result?.status === 'ok') {
            console.log(`✅ Qdrant Sync Successful!`);
        } else {
            console.error(`❌ Qdrant Sync Failed:`, result);
        }
    }
}

// Main Execution
if (require.main === module) {
(async () => {
    console.log("\x1b[36m🧠 AgentDoc: Scanning codebase...\x1b[0m");
    const rootDir = process.cwd();
    const files = await scanDir(rootDir);
    const mapData = {};

    await Promise.all(files.map(async (file) => {
        const content = await fs.promises.readFile(file, 'utf-8');
        const tags = extractTags(content);
        if (tags.length > 0) {
            const relativePath = path.relative(rootDir, file);
            mapData[relativePath] = tags;
        }
    }));

    // 1. Generate Markdown (Legacy/Quick View)
    const output = generateMarkdown(mapData);
    const outputPath = path.join(rootDir, CONFIG.outputFile);
    const outputDir = path.dirname(outputPath);
    await fs.promises.mkdir(outputDir, { recursive: true });
    await fs.promises.writeFile(outputPath, output);
    console.log(`\x1b[32m✅ System Map generated at: ${CONFIG.outputFile}\x1b[0m`);

    // 2. Sync to Qdrant (Vector Memory)
    if (process.argv.includes('--qdrant')) {
        await syncToQdrant(mapData);
    } else {
        console.log(`ℹ️  Run with --qdrant to sync with Vector Database.`);
    }
})();
}

module.exports = {
    CONFIG,
    scanDir,
    extractTags,
    generateMarkdown,
    qdrantRequest,
    ensureCollection,
    mockEmbedding,
    syncToQdrant
};
