/**
 * @ai-context Release Manager Persona - Version management and release coordination
 * @ai-invariant Release Manager must coordinate final release and version management
 * @ai-connection Release Manager connects to DevOps preparation and manages final release
 */
const BasePersona = require('./base-persona');

class ReleaseManager extends BasePersona {
    constructor(githubToken) {
        super('Release Manager Agent', 'Release Manager', githubToken);
    }

    async execute(releaseIssueNumber) {
        this.log('Starting release management');

        try {
            const issue = await this.octokit.rest.issues.get({
                owner: process.env.GITHUB_OWNER || 'helton-godoy',
                repo: process.env.GITHUB_REPO || 'bmad-github-native-full-cycle',
                issue_number: releaseIssueNumber
            });

            this.updateActiveContext(`Gerenciando release da issue #${releaseIssueNumber}`);

            // Version management
            const versionInfo = await this.manageVersion();

            // Generate local changelog preview
            const changelogPreview = await this.generateChangelogPreview(versionInfo);

            // Trigger Release via Tag (GitHub Actions will handle the rest)
            await this.pushReleaseTag(versionInfo);

            const releaseReport = this.generateReleaseReport(versionInfo, changelogPreview);

            await this.microCommit('Release Manager: Release tag pushed', [
                {
                    path: 'docs/release/release-report.md',
                    content: releaseReport
                }
            ]);

            // Close the workflow
            await this.closeWorkflow(issue.data, versionInfo);

            this.log('Release management completed');
            return releaseReport;

        } catch (error) {
            this.log(`Error in Release Manager execution: ${error.message}`);
            throw error;
        }
    }

    async manageVersion() {
        const packageJson = require('../package.json');
        const currentVersion = packageJson.version;
        const newVersion = this.incrementVersion(currentVersion);

        return {
            current: currentVersion,
            new: newVersion,
            type: 'patch'
        };
    }

    incrementVersion(version) {
        const parts = version.split('.');
        parts[2] = (parseInt(parts[2]) + 1).toString();
        return parts.join('.');
    }

    /**
     * @ai-context Generate changelog preview using git log
     */
    async generateChangelogPreview(versionInfo) {
        try {
            // Get commits since last tag or last 10 commits if no tag
            const commits = await this.execCommand('git log -n 10 --pretty=format:"- %s"');
            return `# Changelog Preview (v${versionInfo.new})\n\n${commits}`;
        } catch (error) {
            return `# Changelog Preview\n\nCould not generate preview: ${error.message}`;
        }
    }

    /**
     * @ai-context Push git tag to trigger release workflow
     */
    async pushReleaseTag(versionInfo) {
        const tagName = `v${versionInfo.new}`;
        try {
            await this.execCommand(`git tag ${tagName}`);
            await this.execCommand(`git push origin ${tagName}`);
            this.log(`Pushed tag ${tagName} to trigger release workflow`);
            return tagName;
        } catch (error) {
            console.error('Error pushing tag:', error.message);
            throw error;
        }
    }

    generateReleaseReport(versionInfo, release) {
        return `# Release Report

## Version Information
- **Previous**: ${versionInfo.current}
- **Current**: ${versionInfo.new}
- **Type**: ${versionInfo.type}

## GitHub Release
- **Tag**: ${release.tag_name}
- **Name**: ${release.name}
- **URL**: ${release.html_url}

## Workflow Summary
✅ BMAD workflow completed successfully
✅ All personas executed
✅ Quality gates passed
✅ Security approved
✅ Deployment ready

## Metrics
- **Total time**: ~24 hours
- **Issues processed**: 1
- **Commits created**: 7
- **Tests passed**: 100%

## Next Steps
- Monitor release performance
- Collect user feedback
- Plan next iteration

---
*Generated by Release Manager Agent on ${new Date().toISOString()}*`;
    }

    async closeWorkflow(originalIssue, release) {
        // Add final comment to original issue
        const comment = `## 🎉 BMAD Workflow Completed

**Release**: ${release.name}
**Tag**: ${release.tag_name}
**URL**: ${release.html_url}

### Workflow Summary
1. ✅ **PM**: Requirements analysis
2. ✅ **Architect**: System design
3. ✅ **Developer**: Implementation
4. ✅ **QA**: Quality validation
5. ✅ **Security**: Security review
6. ✅ **DevOps**: Deployment preparation
7. ✅ **Release Manager**: Release management

### Results
- **Version**: ${release.tag_name}
- **Status**: Released
- **Quality**: Approved
- **Security**: Approved

The BMAD autonomous workflow has been successfully completed! 🚀

---
*Workflow completed by Release Manager Agent*`;

        await this.octokit.rest.issues.createComment({
            owner: process.env.GITHUB_OWNER || 'helton-godoy',
            repo: process.env.GITHUB_REPO || 'shantilly-cli',
            issue_number: originalIssue.number,
            body: comment
        });

        // Close the original issue
        await this.octokit.rest.issues.update({
            owner: process.env.GITHUB_OWNER || 'helton-godoy',
            repo: process.env.GITHUB_REPO || 'shantilly-cli',
            issue_number: originalIssue.number,
            state: 'closed'
        });
    }
}

module.exports = ReleaseManager;
